version: "3.6"
services:
  web:
    build: .
    image: registry.dis.cwi.nl/annemo
    restart: always
    volumes:
      - ./results:/code/results
      - ./static/videos:/code/static/videos
      - ./config.json:/code/config.json
    ports:
      - "3001:3001"
    command: sh -c "yarn start"
